version: 0.2

env:
  variables:
    TF_VERSION: "1.15.6"

phases:
  install:
    commands:
      - wget -q https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - mkdir -p /tmp/tf && unzip -o terraform_${TF_VERSION}_linux_amd64.zip -d /tmp/tf
      - mv /tmp/tf/terraform /usr/local/bin/terraform

  build:
    commands:
      - cd terraform
      - terraform init
      - terraform validate
      - terraform apply -auto-approve
